### ISSUE TITLE
Meeting 03.04.2023

### ISSUE THREAD

**Issue by justinexner** [top-22/forum#12]
- Vorstellung der Ergebnisse vom Deployment der Webseite durch Docker, Github und auf Server -> [forum.jeschek.eu](http://forum.jeschek.eu/)
- Besprechung des Grundgerüst mit allen Beteiligten
- Code Formatter mit yarn format oder yarn check-format hinzugefügt um unser Projekt einheitlicher zu halten
- [Read.me](http://read.me/) ist out of date und wird pdated
- Aufgabenverteilung bis zum 17.04.2023:
	User Authentication (Tom, Philip)
	Room Seite (Joni)
	CreateAPost (Sarah)
	CreateARoom (Josh)
	Navbar (Justin) + Home (Justin)
- Offen bleiben:
	Join Room ()
	Thread Seite ()

**Comment by joshuajeschek** [comment]
wieso ist das hier ein offenes issue xd
